// <auto-generated />
using System;
using IzolluVakfi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IzolluVakfi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251220100835_AddMeetingNotesAndAttendanceStatus")]
    partial class AddMeetingNotesAndAttendanceStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("IzolluVakfi.Data.Entities.ActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Detay")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("IslemTipi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("IzolluVakfi.Data.Entities.Aid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AcademicYear")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Adres")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsIzollulu")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Koy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notlar")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("RefereEden")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sehir")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Aids");
                });

            modelBuilder.Entity("IzolluVakfi.Data.Entities.Donor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Adres")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BirimBursTutari")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BursAdedi")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("BursVermeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Firma")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("IlkBursVerdigiTarih")
                        .HasColumnType("TEXT");

                    b.Property<string>("Meslek")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notlar")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sektor")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sirket")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SonBursVerdigiTarih")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ToplamTutar")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Donors");
                });

            modelBuilder.Entity("IzolluVakfi.Data.Entities.Meeting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BitisTarihi")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Konum")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToplantiNotlari")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToplantiTuru")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Meetings");
                });

            modelBuilder.Entity("IzolluVakfi.Data.Entities.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Adres")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BursVeriyor")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DogumTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Durum")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Firma")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDenetimKurulu")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsIzollulu")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMutevelli")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsYonetimKurulu")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Koy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("MembershipPeriod")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Meslek")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notlar")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RoleEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RoleStartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SicilNumarasi")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TCNo")
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UyelikBaslangicTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("UyelikTuru")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Yas")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SicilNumarasi")
                        .IsUnique();

                    b.ToTable("Members");
                });

            modelBuilder.Entity("IzolluVakfi.Data.Entities.MemberMeetingAttendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Katildi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mazeret")
                        .HasColumnType("TEXT");

                    b.Property<int>("MeetingId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MemberId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MeetingId");

                    b.HasIndex("MemberId");

                    b.ToTable("MemberMeetingAttendances");
                });

            modelBuilder.Entity("IzolluVakfi.Data.Entities.MemberScholarshipCommitment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AcademicYear")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("GivenCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MemberId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("PledgedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TermId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("YearlyAmountPerScholarship")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.ToTable("MemberScholarshipCommitments");
                });

            modelBuilder.Entity("IzolluVakfi.Data.Entities.ScholarshipPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CommitmentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StudentId1")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TermId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CommitmentId")
                        .HasDatabaseName("IX_ScholarshipPayments_CommitmentId");

                    b.HasIndex("PaymentDate")
                        .HasDatabaseName("IX_ScholarshipPayments_PaymentDate");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("IX_ScholarshipPayments_StudentId");

                    b.HasIndex("StudentId1");

                    b.ToTable("ScholarshipPayments");
                });

            modelBuilder.Entity("IzolluVakfi.Data.Entities.Settings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("IzolluVakfi.Data.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Adres")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("AktifBursMu")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AylikTutar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BagisciAdi")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Bolum")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BursBaslangicTarihi")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BursBitisTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cinsiyet")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DogumTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("EbeveynAdi")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("EbeveynTelefon")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Firma")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("IBAN")
                        .HasMaxLength(34)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsIzollulu")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMalatyaUniversity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Koy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Meslek")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("MezunMu")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("MezuniyetTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notlar")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Referans")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ScholarshipCutDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScholarshipCutReason")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SicilNumarasi")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Sinif")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TCNo")
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ToplamAlinanBurs")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TranskriptNotu")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Universite")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Yas")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SicilNumarasi")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("IzolluVakfi.Data.Entities.StudentMeetingAttendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Katildi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mazeret")
                        .HasColumnType("TEXT");

                    b.Property<int>("MeetingId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MeetingId");

                    b.HasIndex("StudentId", "MeetingId")
                        .IsUnique();

                    b.ToTable("StudentMeetingAttendances");
                });

            modelBuilder.Entity("IzolluVakfi.Data.Entities.SystemSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ActiveTermId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AppVersion")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SystemSettings");
                });

            modelBuilder.Entity("IzolluVakfi.Data.Entities.Term", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("End")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Start")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Terms");
                });

            modelBuilder.Entity("IzolluVakfi.Data.Entities.TermScholarshipConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MonthlyAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("TermId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("YearlyAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("TermId");

                    b.ToTable("TermScholarshipConfigs");
                });

            modelBuilder.Entity("IzolluVakfi.Data.Entities.TranscriptRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("GNO")
                        .HasColumnType("decimal(3,2)");

                    b.Property<DateTime>("GirisTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notlar")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PdfDosyaYolu")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("TranscriptRecords");
                });

            modelBuilder.Entity("IzolluVakfi.Data.Entities.Village", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int?>("IlkokulOgrenciSayisi")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LiseOgrenciSayisi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MuhtarAdi")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("MuhtarTelefon")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notlar")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Nufus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int?>("OrtaokulOgrenciSayisi")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UniversiteOgrenciSayisi")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Villages");
                });

            modelBuilder.Entity("IzolluVakfi.Data.Entities.MemberMeetingAttendance", b =>
                {
                    b.HasOne("IzolluVakfi.Data.Entities.Meeting", "Meeting")
                        .WithMany("MemberAttendances")
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IzolluVakfi.Data.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meeting");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("IzolluVakfi.Data.Entities.MemberScholarshipCommitment", b =>
                {
                    b.HasOne("IzolluVakfi.Data.Entities.Member", "Member")
                        .WithMany("ScholarshipCommitments")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("IzolluVakfi.Data.Entities.ScholarshipPayment", b =>
                {
                    b.HasOne("IzolluVakfi.Data.Entities.MemberScholarshipCommitment", "Commitment")
                        .WithMany()
                        .HasForeignKey("CommitmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IzolluVakfi.Data.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IzolluVakfi.Data.Entities.Student", null)
                        .WithMany("ScholarshipPayments")
                        .HasForeignKey("StudentId1");

                    b.Navigation("Commitment");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("IzolluVakfi.Data.Entities.StudentMeetingAttendance", b =>
                {
                    b.HasOne("IzolluVakfi.Data.Entities.Meeting", "Meeting")
                        .WithMany("Attendances")
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IzolluVakfi.Data.Entities.Student", "Student")
                        .WithMany("MeetingAttendances")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meeting");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("IzolluVakfi.Data.Entities.TermScholarshipConfig", b =>
                {
                    b.HasOne("IzolluVakfi.Data.Entities.Term", "Term")
                        .WithMany()
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Term");
                });

            modelBuilder.Entity("IzolluVakfi.Data.Entities.TranscriptRecord", b =>
                {
                    b.HasOne("IzolluVakfi.Data.Entities.Student", "Student")
                        .WithMany("Transcripts")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("IzolluVakfi.Data.Entities.Meeting", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("MemberAttendances");
                });

            modelBuilder.Entity("IzolluVakfi.Data.Entities.Member", b =>
                {
                    b.Navigation("ScholarshipCommitments");
                });

            modelBuilder.Entity("IzolluVakfi.Data.Entities.Student", b =>
                {
                    b.Navigation("MeetingAttendances");

                    b.Navigation("ScholarshipPayments");

                    b.Navigation("Transcripts");
                });
#pragma warning restore 612, 618
        }
    }
}
