// <auto-generated />
using System;
using IzolluVakfi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IzolluVakfi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251113221622_FixToplamAlinanBursColumnType")]
    partial class FixToplamAlinanBursColumnType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("IzolluVakfi.Data.Entities.ActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Detay")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("IslemTipi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("IzolluVakfi.Data.Entities.Donor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Adres")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BirimBursTutari")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BursAdedi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Firma")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("IlkBursVerdigiTarih")
                        .HasColumnType("TEXT");

                    b.Property<string>("Meslek")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notlar")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sektor")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sirket")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SonBursVerdigiTarih")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Donors");
                });

            modelBuilder.Entity("IzolluVakfi.Data.Entities.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Adres")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDenetimKurulu")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMutevelli")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsYonetimKurulu")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Meslek")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notlar")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("IzolluVakfi.Data.Entities.Period", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BitisTarihi")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Periods");
                });

            modelBuilder.Entity("IzolluVakfi.Data.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Adres")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("AktifBursMu")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AylikTutar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BagisciAdi")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Bolum")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BursBaslangicTarihi")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BursBitisTarihi")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DogumTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Donem")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("EbeveynAdi")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("EbeveynTelefon")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Koy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Meslek")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("MezunMu")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("MezuniyetTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notlar")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Referans")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SicilNumarasi")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Sinif")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TCNo")
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ToplamAlinanBurs")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Universite")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Yas")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("IzolluVakfi.Data.Entities.TranscriptRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("GNO")
                        .HasColumnType("decimal(3,2)");

                    b.Property<DateTime>("GirisTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notlar")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("TranscriptRecords");
                });

            modelBuilder.Entity("IzolluVakfi.Data.Entities.TranscriptRecord", b =>
                {
                    b.HasOne("IzolluVakfi.Data.Entities.Student", "Student")
                        .WithMany("Transcripts")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("IzolluVakfi.Data.Entities.Student", b =>
                {
                    b.Navigation("Transcripts");
                });
#pragma warning restore 612, 618
        }
    }
}
